/**
 * @file BuildInfo.h
 * @brief Build information automatically updated by git hooks
 *
 * This file is automatically generated by the post-commit git hook.
 * Do not edit manually - your changes will be overwritten.
 */

#ifndef BUILDINFO_H
#define BUILDINFO_H

#define GIT_COMMIT_HASH "ad2c3d1"
#define BUILD_TIMESTAMP "2026-07-29 05:45:05"

#endif // BUILDINFO_H
