/**
 * @file BuildInfo.h
 * @brief Build information automatically updated by git hooks
 *
 * This file is automatically generated by the pre-commit git hook and is
 * committed along with the change. Do not edit manually - your edits will be
 * overwritten.
 *
 * GIT_COMMIT_HASH names the PARENT of the commit that contains this file. A
 * commit cannot record its own hash, because the hash is derived from the tree
 * that this file is part of.
 */

#ifndef BUILDINFO_H
#define BUILDINFO_H

#define GIT_COMMIT_HASH "f58d443"
#define BUILD_TIMESTAMP "2026-07-31 16:46:20"

#endif // BUILDINFO_H
